apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-proxy-deploy
spec:
  selector:
    matchLabels:
      app: market-proxy-deploy
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: market-proxy-deploy
    spec:
      containers:
        - name: market-proxy-deploy
          image: ghcr.io/fox-foundation/market-proxy:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: market-proxy-config
          env:
            - name: PROXYD_PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: market-proxy-secrets
                  key: gecko-api-key
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "3000m"
          ports:
            - containerPort: 8000
              name: http
